# Generated by Django 6.0.3 on 2026-03-13 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reconcile_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='other_category_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('education', 'Education'), ('sports', 'Sports'), ('disaster', 'Disaster Relief'), ('ngo', 'NGO'), ('animals', 'Animal Welfare'), ('community', 'Community Development'), ('memorial', 'Memorial'), ('birthday', 'Birthday'), ('marathon', 'Marathon'), ('wedding', 'Wedding'), ('environment', 'Environment'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('relationship_proof', 'Relationship Proof'), ('gst_cert', 'GST Certificate'), ('80g_cert', '80G Certificate'), ('fcra_cert', 'FCRA Certificate'), ('selfie', 'Selfie Upload'), ('bank_passbook', 'Bank Passbook Front Page')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='campaigns/gallery/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.campaign')),
            ],
        ),
    ]
