# Generated by Django 6.0.3 on 2026-03-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_campaigndocument_document_url_and_more'),
    ]

    operations = [
        # User Lockout fields
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        # VerificationAssignment additions and updates
        migrations.AddField(
            model_name='verificationassignment',
            name='beneficiary_verified',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='verificationassignment',
            name='site_visit_conducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationassignment',
            name='story_accuracy',
            field=models.CharField(blank=True, choices=[('accurate', 'Accurate'), ('partial', 'Partial'), ('inaccurate', 'Inaccurate')], max_length=15, null=True),
        ),
        # Remove old bool fields if they exist (we'll see if this fails)
        migrations.RemoveField(
            model_name='verificationassignment',
            name='site_visit_done',
        ),
        migrations.RemoveField(
            model_name='verificationassignment',
            name='story_accurate',
        ),
        # Alter existing bool to char
        migrations.AlterField(
            model_name='verificationassignment',
            name='documents_authentic',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('suspicious', 'Suspicious')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verificationassignment',
            name='identity_verified',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial')], max_length=10, null=True),
        ),
    ]
