# Generated by Django 6.0.3 on 2026-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_volunteer_module_v1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndocument',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='campaignimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='campaignupdate',
            name='image_url',
        ),
        migrations.AddField(
            model_name='campaigndocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/documents/'),
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/images/'),
        ),
        migrations.AddField(
            model_name='campaignupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/updates/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc/front/'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='verifications/documents/'),
        ),
        migrations.AlterField(
            model_name='withdrawaldocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='withdrawals/documents/'),
        ),
        migrations.AlterField(
            model_name='withdrawaldocument',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
    ]
