# Generated by Django 6.0.3 on 2026-03-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_campaigndocument_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
