# Generated by Django 6.0.3 on 2026-03-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_donation_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
