# Generated by Django 6.0.3 on 2026-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='destination_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='destination_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='destination_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='destination_ifsc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
